#####
name: CycleGan
visdom: False
port: 6022   #  port parameters
save_root: './output/Cyc_0824/C_cnn_51_2/'
image_save: './output/Cyc_0824/C_cnn_51_2/img/'

# lamda weight
Adv_lamda: 1
Cyc_lamda: 10
VGG_lamda: 2
Aux_lamda: 0.1
Id_lamda: 5

epoch: 0        # starting epoch
n_epochs: 300       # How often do you want to display output images during training
clustering_epochs: 150
batchSize: 8         
dataroot: "./datasets/USenhance/train"     # root directory of the dataset
val_dataroot: "./datasets/USenhance/valid"
lr: 0.0001                   # initial learning rate
decay_epoch: 20            # epoch to start linearly decaying the learning rate to 0
cropsize: 256             # size of the data crop
size: 256                
input_nc: 1         
output_nc: 1                  
cuda: True                
n_cpu: 8
grad_clip: 5
pretrain: False
device_ids: [0]

## inference
model_root: './output/Cyc_0824/C_cnn_51_2/0289_netG_A2B.pth'
model_root2: './output/Cyc_0824/C_cnn_51_2/0299_netG_A2B.pth'
infer_dataroot: './datasets/submission/low_quality_images'
infer_image_save: './datasets/submission/C_cnn_51_2/high_quality_images_289_299'
